### ISSUE TITLE
Feature: 为脚手架nb-cli提供插件卸载和更换nonebot2版本（降级）功能

### ISSUE THREAD

**Issue by Jerry-FaGe** [nonebot/nb-cli#1]
**是否在使用中遇到某些问题而需要新的特性？请描述：**

如题，虽然可以通过pip直接卸载插件的python包但是不确定是否有其他依赖问题，而且主文件`bot.py`内自动添加的加载插件语句也不会自动删除，可能会导致不熟悉python的人不知道怎么解决。

因为很多插件并不能及时的支持新版本nonebot2（而nb-cli是默认安装最新版本），导致版本更新后新用户安装部署完成发现并没有几个插件能用，所以也希望nb-cli能支持更换（降级）nonebot2的版本，同理，虽然可以通过pip直接降级nonebot2的python包但是不确定是否有其他依赖问题。

**描述你所需要的特性：**

同上

**Comment by yanyongyu** [comment]
由于nb-cli不同版本适配的nonebot2版本也不相同，这个功能可能目前不可行，同样的关于插件适配版本也不受nb-cli控制，这个应该前往插件相应文档、依赖说明确认
