### ISSUE TITLE
Bug: 重载忽略文件夹不支持相对路径

### ISSUE THREAD

**Issue by fu050409** [nonebot/nb-cli#122]
```
root@hcss-ecs-ccfa:~# nb run --help
Usage: nb run [OPTIONS]

  Run the bot in current folder.

Options:
  -f, --file TEXT         Exist entry file of your bot.  [default: bot.py]
  -r, --reload            Reload the bot when file changed.
  --reload-dirs TEXT      Paths to watch for changes.
  --reload-includes TEXT  Files to watch for changes.
  --reload-excludes TEXT  Files to ignore for changes.
  --reload-delay FLOAT    Delay time for reloading in seconds.  [default: 0.5]
  -h, --help              Show this message and exit.
```

重载的时候有特定的文件夹不需要被监视重载，但是看起来`nb-cil`没有提供对整个文件夹忽略的功能，而只能指定忽略特定文件。

能否在重载时加入忽略监视的文件夹？例如：

```
nb run --reload --reload-excludes-dirs packages/
```

**Comment by yanyongyu** [comment]
有的哦
https://github.com/nonebot/nb-cli/blob/74c8c2b2f81c99affb76bbddb31b4f3b66719048/nb_cli/handlers/reloader.py#L29-L45

**Comment by fu050409** [comment]
我尝试了以下操作：
```
PS D:\Projects\noctisdice> nb run --reload --reload-excludes packages/
```

Nonebot 正常启动了，随后我对`packages/ndice/src/ndice.py`进行了修改，我却得到了：

```
Watchfiles 在 "packages\ndice\src\ndice.py" 中发现变化. 正在重新加载...
04-01 16:22:51 [INFO] uvicorn | Shutting down
04-01 16:22:51 [INFO] uvicorn | Waiting for application shutdown.
04-01 16:22:51 [INFO] uvicorn | Application shutdown complete.
04-01 16:22:51 [INFO] uvicorn | Finished server process [7416]
```

**Comment by fu050409** [comment]
我找到问题所在了，`nb-cli`看起来不支持相对路径进行忽略，我将指令修改为`nb run --reload --reload-excludes D:/projects/noctisdice/packages`后它便运行正常了。

感谢你的耐心。

**Comment by yanyongyu** [comment]
相对路径也是相对当前工作目录，你可以看看你的工作目录对不对

**Comment by fu050409** [comment]
> 我尝试了以下操作：
> 
> ```
> PS D:\Projects\noctisdice> nb run --reload --reload-excludes packages/
> ```

> Watchfiles 在 "packages\ndice\src\ndice.py" 中发现变化. 正在重新加载...

> 我找到问题所在了，nb-cli看起来不支持相对路径进行忽略，我将指令修改为nb run --reload --reload-excludes D:/projects/noctisdice/packages后它便运行正常了。

> 相对路径也是相对当前工作目录，你可以看看你的工作目录对不对

我的工作目录是`D:\Projects\noctisdice`，而修改的文件是`packages\ndice\src\ndice.py`，忽略监听`--reload-excludes`的文件夹是`packages/`。

看起来我的工作目录没有问题？

**Comment by yanyongyu** [comment]
看上去是漏了resolve
