### ISSUE TITLE
是否有一键搭建bot的命令？

### ISSUE THREAD

**Issue by N1ghtss** [nonebot/nb-cli#135]
是否可以在nb create中指定适配器、驱动器等参数？
图中的template是根据模板文件来创建bot吗，项目模板文件的格式是怎么样的？
![image](https://github.com/user-attachments/assets/5aec01ea-44a7-4747-8a9b-7cf324fd3b8e)

**Comment by yanyongyu** [comment]
你直接 nb create 就可以了啊

**Comment by N1ghtss** [comment]
> 你直接 nb create 就可以了啊

就是想跳过nb create 中选择的步骤

**Comment by yanyongyu** [comment]
目前并不可以跳过，也不支持通过参数传递的方式

**Comment by N1ghtss** [comment]
> 目前并不可以跳过，也不支持通过参数传递的方式

好的，感谢回答
