### ISSUE TITLE
Bug:安装成功后输入nb提示命令不存在

### ISSUE THREAD

**Issue by TsinbeiTech** [nonebot/nb-cli#16]
使用`pip3 install nb-cli`安装后，输入nb提示`-bash: nb: command not found`
这是什么原因？
![image](https://user-images.githubusercontent.com/79034142/130770300-e402df63-f525-4cf5-937e-995f401106bd.png)
![image](https://user-images.githubusercontent.com/79034142/130770350-1fa4bf3d-fdb6-4a05-8290-f59c83f82d19.png)

**Comment by yanyongyu** [comment]
请检查你的环境变量或者使用`python3 -m nb_cli`

**Comment by TsinbeiTech** [comment]
谢谢您的耐心解答。
通过检查我发现是依赖冲突导致的，解决问题后可以使用`python3 -m nb_cli`正常使用。
