### ISSUE TITLE
Bug: `nb create` 生成的 `pyproject.toml` 中 python 版本与项目要求不一致

### ISSUE THREAD

**Issue by d-w-x** [nonebot/nb-cli#18]
当前最多只支持到 python 3.7.3， 当前 python 已经推出到 3.9.7，能否测试项目对多版本的兼容并放开 python 版本？

系统版本： 3.9.7， poetry版本：最新。
错误：

~~~txt
  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For nonebot-adapter-cqhttp, a possible solution would be to set the `python` property to ">=3.7.3,<4.0"
~~~

**Comment by mnixry** [comment]
已提交 #19 进行修复, 相关代码:
https://github.com/nonebot/nb-cli/blob/b4175b5cdbdc2c3ed9960d40ce8585402ffc99bb/nb_cli/project/%7B%7Bcookiecutter.project_slug%7D%7D/pyproject.toml#L8-L11

**Comment by d-w-x** [comment]
感谢，有必要的话请推进 nb-clib 版本并在 npmjs.org 中更新以便新用户能使用到新版本（避免新用户出现类似问题被当场劝退。）

**Comment by StarHeartHunt** [comment]
> 感谢，有必要的话请推进 nb-clib 版本并在 npmjs.org 中更新以便新用户能使用到新版本（避免新用户出现类似问题被当场劝退。）

nb-cli 是使用 Python 编写的，与 npmjs.org 这一 JavaScript 包仓库无关，会很快在 pypi.org 上发布新版本更新

**Comment by d-w-x** [comment]
哦哦，混了混了。

感谢。
