### ISSUE TITLE
RuntimeError('Config file pyproject.toml does not exist!')

### ISSUE THREAD

**Issue by asoulbella** [nonebot/nb-cli#21]
**描述问题：**

在运行nb plugin install nonebot_plugin_docs时安装失败，安装程序提示异常，错误如下
RuntimeError('Config file pyproject.toml does not exist!')

**环境信息：**

 - OS: WSL-Ubuntu20
 - Python Version: [e.g. 3.8]
 - Nonebot Version: 2.0.0a15

**截图或日志**

![image](https://user-images.githubusercontent.com/24636140/135541909-8870ae35-2fda-48a0-a670-9223d4ffe111.png)

**Comment by yanyongyu** [comment]
你没有使用nb_cli创建项目或者未在项目目录下安装插件

**Comment by OriKnights** [comment]
那么如何解决这个问题呢😢

**Comment by yanyongyu** [comment]
在项目目录(bot.py所在目录)下使用nbcli

**Comment by FSWei** [comment]
thank you so much！
