### ISSUE TITLE
pdm 无法识别默认的 requires-python

### ISSUE THREAD

**Issue by MeetWq** [nonebot/nb-cli#51]
生成的 pyproject.toml 中 `requires-python` 默认为  `"^3.8"`，pdm 无法识别

```
$ pdm update
python.use_venv is on, creating a virtualenv for this project...
[InvalidPyVersion]: Invalid specifier: '^3.8'
```

**Comment by yanyongyu** [comment]
应该是`>=3.8, <4.0`（poetry生成的忘记改了

**Comment by yanyongyu** [comment]
fixed in https://github.com/nonebot/nb-cli/commit/f5fe346f8deeb5446301e24de1077f7ebc7a69c0
