### ISSUE TITLE
Question: project name 无法确认

### ISSUE THREAD

**Issue by Wansn-w** [nonebot/nb-cli#52]
版本 `nb-cli@latest`
在执行 ` nb create ` 时若project name为数字，则无法正确更新出下一行prompt。
![Screenshot_2023-01-15-23-12-50-535_com.termux.jpg](https://user-images.githubusercontent.com/49867372/212549882-1c8776e2-2ba3-4dbb-939c-f9f9bf20e5b9.jpg)

---

版本 `nb-cli@0.6.8` 正常。
![Screenshot_2023-01-15-23-22-04-389_com.termux.jpg](https://user-images.githubusercontent.com/49867372/212549896-4214c8cc-cdb5-4b89-b742-2538cfeddc5e.jpg)

**Comment by yanyongyu** [comment]
不允许数字开头的项目名，这不是合法Python包名

**Comment by Wansn-w** [comment]
如果可能 请添加一点文本描述
~~这个问题困扰了我朋友很久 **他非要用114514 as project name**~~

**Comment by Wansn-w** [comment]
不添加适当的文本描述对于新手来说是残酷的。对于没有经验的新手，往往会简单的使用数字而不是helloworld等作为项目名 ---- 而他们也不需要真正创建符合标准的项目，需要的只是尽可能快且简单地开始。于我朋友而言，他仅仅是需要运行[Haruka Bot](https://github.com/SK-415/HarukaBot)。

**Comment by yanyongyu** [comment]
目前noneprompt暂不支持显示提示，可能之后会考虑吧

**Comment by Wansn-w** [comment]
先close了 以后加doc里吧
