### ISSUE TITLE
nb create时，选择none驱动器与其它不支持Mixin驱动器的不兼容问题

### ISSUE THREAD

**Issue by dixiatielu** [nonebot/nb-cli#59]
### 系统环境
- Ubuntu 22.04 64位
- Python 3.10.6
- nb-cli 1.0.2（通过pipx安装）
### 复现步骤
1. 执行`nb create`
2. 在选择driver时同时选择None驱动器与任意不支持Mixin的驱动器（FastAPI、Quart）
3. 剩余选项全部选择默认选项
4. 进入机器人目录，执行`nb run`

### 报错

```
root@iZf8zb8rb6ykcca1t6gmdbZ:~/dxtl_bot/dxtlBot# nb run --reload
Started reloader with process [7417].
01-26 15:14:47 [SUCCESS] nonebot | NoneBot is initializing...
01-26 15:14:47 [INFO] nonebot | Current Env: prod
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/root/dxtl_bot/dxtlBot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 256, in init
    DriverClass = _resolve_combine_expr(config.driver)
  File "/root/dxtl_bot/dxtlBot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 201, in _resolve_combine_expr
    mixins = [
  File "/root/dxtl_bot/dxtlBot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 202, in <listcomp>
    _resolve_dot_notation(mixin, "Mixin", default_prefix="nonebot.drivers.")
  File "/root/dxtl_bot/dxtlBot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 186, in _resolve_dot_notation
    return getattr(module, default_attr)
AttributeError: module 'nonebot.drivers.fastapi' has no attribute 'Mixin'
Shutting down process [7417]...
Stopped reloader.
```

经过实验，如果在`nb create`时单独选择安装None驱动器，成功创建后再进入机器人目录通过`nb driver install FastAPI`则不会出现此问题，先安装FastAPI启动器，再安装None同样不会触发。仅在create时同时选择None和不支持Mixin的驱动器才会出现此问题。个人判断更可能是nb-cli导致的问题，若issue更应投至nonebot2仓库下，请告知，谢谢！

**Comment by yanyongyu** [comment]
这个问题目前没法解决，只能用户自己判断应该选择哪个driver

**Comment by dixiatielu** [comment]
> 这个问题目前没法解决，只能用户自己判断应该选择哪个driver

好的，是否可以在文档中加个提醒呢？可能有像我这样的用户不了解情况，创建项目时想把能选的全选上导致出现奇奇怪怪的问题😂

**Comment by yanyongyu** [comment]
新的文档在路上了

**Comment by 2catycm** [comment]
文档都没有解释不同驱动器时干什么的，我一个新手阅读了半天懵逼了，为什么驱动器可以有很多个在一个项目里面？

**Comment by 2catycm** [comment]
我就想要对接go-cqhttp， 我翻了半天文档，搞不明白到底要怎么配置，有没有人教下我

**Comment by 2catycm** [comment]
fastapi不是一个服务器框架吗，为什么是一个驱动器？

**Comment by yanyongyu** [comment]
如果你不想了解驱动器的具体定义，你可以直接参考适配器文档配置驱动器，如适配器无特殊说明，使用默认驱动器即可。
如果你想要了解驱动器具体内容，请查看文档https://nonebot.dev/docs/advanced/driver

**Comment by KomoriDev** [comment]
![Screenshot_2023-12-25-19-27-06-654_com android chrome](https://github.com/nonebot/nb-cli/assets/110453675/1cff7655-2989-43f4-84ba-9794d4566714)
（询问驱动器的知识怎么跑到 nb-cli 这里了）

**Comment by 2catycm** [comment]
> 为什么驱动器可以有很多个在一个项目里面？

原来在`进阶`里面，感觉这个文档对新手不太友好，不够渐进式。前面`指南`部分的例子都跑不通，不理解是什么意思。

**Comment by 2catycm** [comment]
> ![Screenshot_2023-12-25-19-27-06-654_com android chrome](https://private-user-images.githubusercontent.com/110453675/292752452-1cff7655-2989-43f4-84ba-9794d4566714.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDQxMDIsIm5iZiI6MTcwMzUwMzgwMiwicGF0aCI6Ii8xMTA0NTM2NzUvMjkyNzUyNDUyLTFjZmY3NjU1LTI5ODktNDNmNC04NGJhLTk3OTRkNDU2NjcxNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMTMwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTJmODA2MGZlOTcxNGRkZjVjMDM2MzZlNTBmNjY3ZjY0NjExN2NkN2U0Yzc5NTNlMDYwMTEyNDhkZjdiNzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._DgKSu-oW_Apub5j55KF8p3Em39krXzV0EdGS__BK8g) （询问驱动器的知识怎么跑到 nb-cli 这里了）

嗯，因为报了这个issue说的错
