### ISSUE TITLE
请问为什么 pywin32 为什么无法导入，各种办法都试了~

### ISSUE THREAD

**Issue by hechushitaoyuan** [nonebot/nb-cli#66]
![image](https://user-images.githubusercontent.com/109302248/221997526-a59ba897-6d9a-47d3-a0a8-7a9ddc42bcd2.png)

**Comment by StarHeartHunt** [comment]
cli 自身有一个 venv，你应该把依赖装到你项目的 venv 里。

**Comment by hechushitaoyuan** [comment]
您好~我尝试在bot.py项目文件夹用nb 选项 安装，但是会提示我已经安装，卸载后发现写的是用户名路径下appdata里面的包，再重新安装也是安在appdata那个路径里面。我也尝试了把两个文件夹复制到 bot.py文件下.Venv\lib\sit-packages 里面，但还是没有作用~vscode启动和CMD 或者powershell启动均无法加载。

**Comment by StarHeartHunt** [comment]
“cli 虚拟环境”指的是 nb-cli 自身的独立于外界的虚拟环境，不是项目的虚拟环境。项目的虚拟环境内的包你可以自己激活环境后使用 pip 安装，也可以用 poetry 或者 pdm 托管。

**Comment by hechushitaoyuan** [comment]
好的~谢谢~已解决~
![image](https://user-images.githubusercontent.com/109302248/222024561-a89c95da-529a-4a44-be98-1f7b4105ffad.png)
