### ISSUE TITLE
Bug: 无法移除 `pyproject.toml` 中的第一个适配器配置项

### ISSUE THREAD

**Issue by NCBM** [nonebot/nb-cli#74]
复现步骤：

1. 进入至少包含一个适配器的项目目录；
2. 使用 `nb-cli` 卸载配置文件中的**第一个适配器**。

预期行为：

相关配置项被移除，适配器被卸载。

实际行为：

相关配置项**未被移除**，但适配器被正常卸载。

该故障在非第一配置的适配器上不存在。

环境信息：

- Linux x86_64
- Python 3.10.10
- nb-cli 1.0.5

额外信息：

已经确定发生此故障时 `nb-cli/config/parser.py#L54-61` 未正常判断。

**Comment by yanyongyu** [comment]
数据呢，你的配置文件内容还有复现步骤

**Comment by yanyongyu** [comment]
哦不需要了，0的问题
