### ISSUE TITLE
关于虚拟环境自动激活的疑问

### ISSUE THREAD

**Issue by Umpire2012** [nonebot/nb-cli#81]
当前环境：WIN11, VS Code, python 3.11 
使用 nb-cli 创建了虚拟环境后 只要打开文件夹或重启shell就可以在 VS Code 里面自动加载，如下图。
![image](https://github.com/nonebot/nb-cli/assets/130277670/e6bf7f6b-b76c-4de3-8049-05e6a608449a)
当使用 Virtualenv 或 venv 等环境时 需要手动激活虚拟环境。
请问项目了有什么操作可以达成自动加载环境吗？烦请不吝赐教，谢谢。

**Comment by yanyongyu** [comment]
在项目目录下使用nb-cli都会自动使用项目虚拟环境

**Comment by Umpire2012** [comment]
https://github.com/pypa/virtualenv/issues/1398 比如在使用某一版本时会出现bug, 请问当前使用了什么版本的 virtualenv ？

**Comment by Umpire2012** [comment]
好的，其实我犯了小白的错误，创建了py文件之后vs code会自动选择环境的。谢谢回复。
