### ISSUE TITLE
raw.fastgit.org证书过期,建议nb-cli仅使用自维护/权威站点

### ISSUE THREAD

**Issue by Moraxyc** [nonebot/nb-cli#84]
执行`nb create`，`获取适配器列表…`时报错如下：

```
ModuleLoadFailed('获取adapter 列表失败.', [SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)'), ConnectTimeout(''), ReadTimeout('')])
```

但该情况时有时无，于是debug模式下发现该文件出错：
https://github.com/nonebot/nb-cli/blob/aec5c94c68cb05106256281bc47356ca784b4ae0/nb_cli/handlers/store.py#L55

经查，`raw.fastgit.org`的证书已于2023/7/3 6:13:13过期
![SSL Certification Details](https://github.com/nonebot/nb-cli/assets/69713071/e294f258-e56d-41e7-9067-c7246c0b5045)

建议`nb-cli`不要使用不稳定的服务作为静态资源站点

**Comment by yanyongyu** [comment]
连接问题建议自行挂代理解决，nb自己使用的cdn在你这也timeout那我们也没办法，我们只能尽可能的提供现有的镜像。另外如果某个镜像出错了并不会影响获取其他镜像的内容，只有全部出错的时候才会报错无法获取。

**Comment by Moraxyc** [comment]
不影响使用，但ssl证书过期而导致的错误在异步请求下确实被抛出了…这可能是httpx库的问题。

这仅仅只是个建议，建议nb-cli不要使用不太稳定的方案防止错误持续抛出

**Comment by yanyongyu** [comment]
如果确认镜像站无法使用或不再维护的话，我们会移除的。
