### ISSUE TITLE
最新版本不支持docker？

### ISSUE THREAD

**Issue by 250king** [nonebot/nb-cli#95]
https://nonebot.dev/docs/best-practice/deployment#docker-%E9%83%A8%E7%BD%B2
但我执行的时候就提升命令不存在？
<img width="263" alt="image" src="https://github.com/nonebot/nb-cli/assets/61256966/fc1fe1f2-9dc3-469d-bf73-68575b630e34">

**Comment by yanyongyu** [comment]
https://nonebot.dev/docs/best-practice/deployment#%E5%AE%89%E8%A3%85%E8%84%9A%E6%89%8B%E6%9E%B6-docker-%E6%8F%92%E4%BB%B6
