### ISSUE TITLE
Feature: 热重载延时

### ISSUE THREAD

**Issue by fu050409** [nonebot/nb-cli#96]
唔，我又来发issue了

关于`nb-cli`中，`nb run --reload`的功能，建议提供重载延时功能。
譬如我的插件中存在自我更新的功能，更新之后`nb-cli`会自动重载整个`Nonebot2`，如果`nb-cli`反应太迅捷的话，部分操作可能尚未完成，能否提供类似`nb run --reload 2`延时两秒重载的功能？

以及，`Nonebot2`那边可否提供重新导入某个插件的方法？这样便于`Nonebot2`在运行的时候在用户层级操作插件。

**Comment by fu050409** [comment]
> python无法无副作用的重新导入模块

但是nonebot是可以实现的，可以把每个插件注册的内容标记，reload的时候重导入……呃，好吧是够麻烦的

**Comment by fu050409** [comment]
但是我说的这个延时重载的功能应该还是挺实用的，看看有没有必要加上

**Comment by yanyongyu** [comment]
热重载延时是可以实现的

**Comment by fu050409** [comment]
> 热重载延时是可以实现的

新版我这边测试无效，它没有进行热重载。不清楚是我这里的问题还是你那边的问题。

指令：
```bash
nb run --reload-delay 2
```
从理论上讲这个应该是延迟两秒，但是它没有应答文件（插件内容）修改而重载。

备注：`nb run --reload`运行正常。

**Comment by yanyongyu** [comment]
reload参数不能省略
